//当前规则文件用于计算个人所得税
package calculation
import com.wangn.java.droosdemo.entity.Calculation

//计算应纳税所得额
rule "tax_setWagemore"
    salience 100
    //设置生效日期
    date-effective "2022-10-01"
    no-loop true
    when
        $cal:Calculation(wage > 0)
    then
        double wagemore = $cal.getWage() - 5000;
        $cal.setWagemore(wagemore);
        update($cal);
end

//设置税率、速算扣除数
rule "tax_3000"
    salience 90
    no-loop true
    activation-group "SETCess_Group"
    when
        $cal:Calculation(wagemore <= 3000)
    then
        $cal.setCess(0.03);//税率
        $cal.setPreminus(0);//速算扣除数
        update($cal);
end

rule "tax_12000"
    salience 90
    no-loop true
    activation-group "SETCess_Group"
    when
        $cal:Calculation(wagemore > 3000 &&wagemore <= 12000)
    then
        $cal.setCess(0.1);//税率
        $cal.setPreminus(210);//速算扣除数
        update($cal);
end


rule "tax_25000"
    salience 90
    no-loop true
    activation-group "SETCess_Group"
    when
        $cal : Calculation(wagemore > 12000 &&wagemore <= 25000)
    then
        $cal.setCess(0.2);
        $cal.setPreminus(1410);
        update($cal);
end

rule "tax_35000"
    salience 90
    no-loop true
    activation-group "SETCess_Group"
    when
        $cal : Calculation(wagemore > 25000 &&wagemore <= 35000)
    then
        $cal.setCess(0.25);
        $cal.setPreminus(2660);
        update($cal);
end

rule "tax_55000"
    salience 90
    no-loop true
    activation-group "SETCess_Group"
    when
        $cal : Calculation(wagemore > 35000 &&wagemore <= 55000)
    then
        $cal.setCess(0.3);
        $cal.setPreminus(4410);
        update($cal);
end

rule "tax_80000"
    salience 90
    no-loop true
    activation-group "SETCess_Group"
    when
        $cal : Calculation(wagemore > 55000 &&wagemore <= 80000)
    then
        $cal.setCess(0.35);
        $cal.setPreminus(7160);
        update($cal);
end

rule "tax_max"
    salience 90
    no-loop true
    activation-group "SETCess_Group"
    when
        $cal : Calculation(wagemore > 80000)
    then
        $cal.setCess(0.45);
        $cal.setPreminus(15160);
        update($cal);
end

rule "tax_result"
    salience 80
    when
        $cal : Calculation(wage > 0 && wagemore > 0 && cess > 0)
    then
        //扣税额
        double wageminus = $cal.getWagemore() * $cal.getCess() - $cal.getPreminus();
        double actualwage = $cal.getWage() - wageminus;
        $cal.setWageminus(wageminus);
        $cal.setActualwage(actualwage);
        System.out.println("--税前工资："+$cal.getWage());
        System.out.println("--应纳税所得额："+$cal.getWagemore());
        System.out.println("--税率：" + $cal.getCess());
        System.out.println("--速算扣除数：" + $cal.getPreminus());
        System.out.println("--扣税额：" + $cal.getWageminus());
        System.out.println("--税后工资：" + $cal.getActualwage());
end