sa-token:
    activity-timeout: -1
    alone-redis:
        database: 2
        host: ${spring.redis.host}
        lettuce:
            pool:
                max-active: ${spring.redis.lettuce.pool.max-active}
                max-idle: ${spring.redis.lettuce.pool.max-idle}
                max-wait: ${spring.redis.lettuce.pool.max-wait}
                min-idle: ${spring.redis.lettuce.pool.min-idle}
        password: ${spring.redis.password}
        port: ${spring.redis.port}
        timeout: ${spring.redis.timeout}
    is-concurrent: true
    is-log: false
    is-print: false
    is-share: false
    max-login-count: -1
    timeout: 2592000
    token-name: token
    token-style: random-32
server:
    port: 8080
spring:
    redis:
        database: 1
        host: 39.106.60.74
        lettuce:
            pool:
                max-active: 200
                max-idle: 10
                max-wait: -1ms
                min-idle: 0
        password: ''
        port: 8379
        timeout: 10s
    trace:
        log:
            format: X-B3-TraceId,X-B3-ParentName

ko-time:
    #需要监测的范围，是链路包含的范围，不仅仅是接口层，参考aop的@pointcut
    pointcut: execution(public * com.wangn.java..*.*(..))

